var expect = require('chai').expect;
var Event = require('../../lib/Event');

var attrs = {"id":1250470802,"title":"PDX Women In Tech (PDXWIT) Coderetreat 2016","description":"\r\nRSVP for this event - https://www.eventbrite.com/e/pdx-women-in-techpdxwit-coderetreat-2016-tickets-27661828273\r\n\r\nPDXWIT presents a woman-focused Coderetreat in honor of the Global Day of Coderetreat 2016. Coderetreat.org is a self-organized, volunteer led organization dedicated to helping software developers help each other improve their craft. Tanya Crenshaw and Jean Richardson will be teaming up to facilitate PDXWIT's 2016 Coderetreat. The Tech Academy is donating space and providing breakfast and lunch for the event.  Come along for a day of codeplay in a supportive environment and help Coderetreat follow the sun during the global celebration of software development!\r\n\r\nHere's how it works: SW developers of all sorts gather together with their machines and IDE's ready to code Conway's Game of Life for 45 minute sessions. Pairs change with every 45 minute iteration so everyone gets exposed to different problem solving strategies, and everyone learns together:  newbies and master-craft persons alike. There is no expectation to finish coding Conway's Game of Life at any point during the day. \r\n\r\nThe purpose is to learn coding problem solving strategies, share skills and experience pairing in a supportive environment. \r\n\r\nPDXWIT a community-based non-profit organization with the purpose of strengthening the Portland women in tech community through educational programs, partnerships and events that provide information, connections, resources, opportunities, and a supportive environment for current and potential women in tech, all of whom are committed to helping each other. Our goal is to bring together and empower current women in tech and encourage others to pursue tech careers to help reduce gender imbalance in the industry and address the current negative effects of that imbalance on women.\r\n","start_time":"2016-10-22T08:00:00.000-07:00","url":"https://www.eventbrite.com/e/pdx-women-in-techpdxwit-coderetreat-2016-tickets-27661828273","created_at":"2016-09-11T20:21:19.000-07:00","updated_at":"2016-09-11T20:21:19.000-07:00","venue_id":202395068,"source_id":null,"duplicate_of_id":null,"end_time":"2016-10-22T17:00:00.000-07:00","version":null,"rrule":null,"venue_details":"","locked":false,"venue":{"id":202395068,"title":"The Tech Academy","description":"","address":"310 SW 4th Ave Suite 412 Portland, OR 97204","url":"http://www.learncodinganywhere.com","created_at":"2015-09-17T14:32:01.000-07:00","updated_at":"2016-08-09T19:48:38.083-07:00","street_address":"310 SW 4th Ave Suite 412","locality":"Portland","region":"OR","postal_code":"97204","country":"USA","latitude":"45.52085","longitude":"-122.6749","email":"info@learncodinganywhere.com","telephone":"5032066915","source_id":null,"duplicate_of_id":null,"closed":false,"wifi":false,"access_notes":"","events_count":24}}

describe("Event", function(){
  var subject = new Event(attrs);

  it("should have verbal description", function(){
    expect(subject.verbalized()).to.equal("At 08:00:00 AM, PDX Women In Tech (PDXWIT) Coderetreat 2016.")
  });

  it("should have card description", function(){
    expect(subject.asCard()).to.equal("PDX Women In Tech (PDXWIT) Coderetreat 2016\nStarts At: 8:00 AM\n310 SW 4th Ave Suite 412 Portland, OR 97204");
  })
});
